sync_interval: 15

pta:
  pta_session: xxx
  problem_set_id: "xx"

gplt:
  output_dir: "./output/gplt"

  excel_path: "./xlsx/gplt.xlsx"
  sheet_name: "template"

  standard_1: 800
  standard_2: 400

xcpcio:
  output_dir: "./output/xcpcio"

  excel_path: "./xlsx/xcpc.xlsx"
  sheet_name: "template"

  start: "XXXX-XX-XX XX:XX:XX"
  end: "XXXX-XX-XX XX:XX:XX"
  frozen_time: 3600
  problem_quantity: 6
  balloon_color:
    - "#FFD700"
    - "#C0C0C0"
    - "#CD7F32"
    - "#FF4500"
    - "#1E90FF"
    - "#32CD32"
  group:
    official: "正式队伍"
    unofficial: "打星队伍"
  medal:
    official:
      gold: 10
      silver: 20
      bronze: 30
  logo:
    preset: "icpc"
